isantimode: false
motd:
  version: "维护 / Maintenance"
  line1: "&bhomo.store"
  line2: "&cQQ群: &e1145141919810"
  logo: "logo.jpg"
kick-message:
  - "&4&l悲报"
  - " "
  - "&bhomo.store &c正在维护 现在可能玩不了了...."
  - " "
  - "&c{REASON}"
  - " "
  - "&c维护将最早在&f{EXP_DATE}&c结束"
  - " "
  - "&c加入官方QQ群:&f1145141919810 &c获得最新消息"
reason: "enable me"
enddate: "00-00-00"